version: '3.3'

services:
  # 数据库服务
  mysql:
    image: mysql:8.0
    container_name: xledger-mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: xledger
    ports:
      - "3314:3306"
    volumes:
      - ./tmp/data/mysql:/var/lib/mysql
    networks:
      - xledger-network

  # Redis 服务
  redis:
    image: redis:6.2
    container_name: xledger-redis
    ports:
      - "6388:6379"
    volumes:
      - redis_data:/data
    networks:
      - xledger-network

  # Swagger UI 服务
  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    container_name: xledger-swagger-ui
    ports:
      - "19901:8080"
    environment:
      SWAGGER_JSON: /openapi.json
      BASE_URL: /
      SWAGGER_UI_BUNDLE_JS: "https://cdn.jsdelivr.net/npm/swagger-ui-dist@5.9.0/swagger-ui-bundle.js"
      SWAGGER_UI_STANDALONE_PRESET_JS: "https://cdn.jsdelivr.net/npm/swagger-ui-dist@5.9.0/swagger-ui-standalone-preset.js"
      SWAGGER_UI_CSS: "https://cdn.jsdelivr.net/npm/swagger-ui-dist@5.9.0/swagger-ui.css"
    volumes:
      - ./document:/usr/share/nginx/html/doc
    networks:
      - xledger-network

networks:
  xledger-network:
    driver: bridge

volumes:
  mysql_data:
  redis_data: