DROP TABLE IF EXISTS transaction_tags;
DROP TABLE IF EXISTS transactions;
DROP TABLE IF EXISTS tags;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS accounts;
DROP TABLE IF EXISTS ledgers;
DROP TABLE IF EXISTS refresh_tokens;
DROP TABLE IF EXISTS users;
