import type { Config } from 'tailwindcss'

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        background: '#f7f9fc',
        surface: '#f7f9fc',
        'surface-bright': '#f7f9fc',
        'surface-dim': '#d8dadd',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f4f7',
        'surface-container': '#eceef1',
        'surface-container-high': '#e6e8eb',
        'surface-container-highest': '#e0e3e6',
        'surface-variant': '#e0e3e6',
        primary: '#00327d',
        'primary-container': '#0047ab',
        'primary-fixed': '#dae2ff',
        'primary-fixed-dim': '#b1c5ff',
        secondary: '#4e5e85',
        'secondary-container': '#c1d1ff',
        tertiary: '#00400f',
        'tertiary-container': '#005a19',
        'tertiary-fixed': '#93f993',
        'tertiary-fixed-dim': '#77dc7a',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        outline: '#737784',
        'outline-variant': '#c3c6d5',
        'on-background': '#191c1e',
        'on-surface': '#191c1e',
        'on-surface-variant': '#434653',
        'on-primary': '#ffffff',
        'on-primary-container': '#a5bdff',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#4a5980',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#6fd372',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
      },
      fontFamily: {
        headline: ['Manrope', 'Inter', 'Microsoft YaHei', 'PingFang SC', 'Noto Sans CJK SC', 'Source Han Sans SC', 'sans-serif'],
        body: ['Inter', 'Microsoft YaHei', 'PingFang SC', 'Noto Sans CJK SC', 'Source Han Sans SC', 'sans-serif'],
        label: ['Inter', 'Microsoft YaHei', 'PingFang SC', 'Noto Sans CJK SC', 'Source Han Sans SC', 'sans-serif'],
      },
      boxShadow: {
        ambient: '0px 12px 32px rgba(25, 28, 30, 0.04)',
      },
      backgroundImage: {
        'primary-gradient': 'linear-gradient(135deg, #00327d 0%, #0047ab 100%)',
      },
      borderRadius: {
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
      },
    },
  },
  plugins: [],
} satisfies Config
